[2024-04-29T13:26:12.672+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-29T13:26:09.469981+00:00 [queued]>
[2024-04-29T13:26:12.682+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-29T13:26:09.469981+00:00 [queued]>
[2024-04-29T13:26:12.682+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2024-04-29T13:26:12.691+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-04-29 13:26:09.469981+00:00
[2024-04-29T13:26:12.694+0000] {standard_task_runner.py:57} INFO - Started process 36 to run task
[2024-04-29T13:26:12.697+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-04-29T13:26:09.469981+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpvxfpxfw3']
[2024-04-29T13:26:12.697+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask extract_data_from_wikipedia
[2024-04-29T13:26:12.741+0000] {task_command.py:410} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-29T13:26:09.469981+00:00 [running]> on host b432030c1483
[2024-04-29T13:26:12.814+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Minh Tran' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T13:26:09.469981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T13:26:09.469981+00:00'
[2024-04-29T13:26:12.815+0000] {logging_mixin.py:149} INFO - Getting wikipedia page... https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2024-04-29T13:26:13.790+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 33, in extract_wikipedia_data
    rows = get_wikipedia_data(html)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 24, in get_wikipedia_data
    table = soup.find_all("table", {"class": "wikitable sortable sticky-header jquery-tablesorter"})[0]
IndexError: list index out of range
[2024-04-29T13:26:13.800+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20240429T132609, start_date=20240429T132612, end_date=20240429T132613
[2024-04-29T13:26:13.813+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task extract_data_from_wikipedia (list index out of range; 36)
[2024-04-29T13:26:13.832+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-04-29T13:26:13.849+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
