[2024-05-01T16:39:45.930+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T16:39:45.962+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-01T16:24:09.436956+00:00 [queued]>
[2024-05-01T16:39:45.971+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-01T16:24:09.436956+00:00 [queued]>
[2024-05-01T16:39:45.971+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T16:39:45.983+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_wikipedia_data> on 2024-05-01 16:24:09.436956+00:00
[2024-05-01T16:39:45.987+0000] {standard_task_runner.py:63} INFO - Started process 4238 to run task
[2024-05-01T16:39:45.989+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'write_wikipedia_data', 'manual__2024-05-01T16:24:09.436956+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmp13c794_r']
[2024-05-01T16:39:45.992+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask write_wikipedia_data
[2024-05-01T16:39:46.074+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-01T16:24:09.436956+00:00 [running]> on host ab8381b78bd9
[2024-05-01T16:39:46.251+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Minh Tran' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='write_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T16:24:09.436956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T16:24:09.436956+00:00'
[2024-05-01T16:39:46.252+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T16:39:46.280+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T16:39:46.281+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 127, in write_wikipedia_data
    filename = ("stadium_cleaned_" + str(datetime.now().date() + "_" + str(datetime.now().time()).replace(":", "_")) + ".csv")
TypeError: unsupported operand type(s) for +: 'datetime.date' and 'str'
[2024-05-01T16:39:46.292+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=write_wikipedia_data, execution_date=20240501T162409, start_date=20240501T163945, end_date=20240501T163946
[2024-05-01T16:39:46.302+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task write_wikipedia_data (unsupported operand type(s) for +: 'datetime.date' and 'str'; 4238)
[2024-05-01T16:39:46.325+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T16:39:46.341+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T16:39:46.342+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
