[2024-05-02T17:07:05.019+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T17:07:05.044+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-02T16:45:34.967560+00:00 [queued]>
[2024-05-02T17:07:05.052+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-02T16:45:34.967560+00:00 [queued]>
[2024-05-02T17:07:05.052+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-02T17:07:05.069+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_wikipedia_data> on 2024-05-02 16:45:34.967560+00:00
[2024-05-02T17:07:05.074+0000] {standard_task_runner.py:63} INFO - Started process 535 to run task
[2024-05-02T17:07:05.076+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'write_wikipedia_data', 'manual__2024-05-02T16:45:34.967560+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpk84lm0d0']
[2024-05-02T17:07:05.078+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask write_wikipedia_data
[2024-05-02T17:07:05.128+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-02T16:45:34.967560+00:00 [running]> on host ac73955389ba
[2024-05-02T17:07:05.279+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Minh Tran' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='write_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T16:45:34.967560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T16:45:34.967560+00:00'
[2024-05-02T17:07:05.279+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T17:07:05.423+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T17:07:05.423+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/adlfs/spec.py", line 505, in do_connect
    raise ValueError(
ValueError: Must provide either a connection_string or account_name with credentials!!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 131, in write_wikipedia_data
    data.to_csv('abfs://footballdataeng@minhfootballproject.dfs.core.windows.get/data/' + filename,
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 430, in _get_filepath_or_buffer
    file_obj = fsspec.open(
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/core.py", line 461, in open
    out = open_files(
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/core.py", line 283, in open_files
    fs, fs_token, paths = get_fs_token_paths(
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/core.py", line 636, in get_fs_token_paths
    fs = filesystem(protocol, **inkwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/registry.py", line 293, in filesystem
    return cls(**storage_options)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/spec.py", line 80, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/adlfs/spec.py", line 334, in __init__
    self.do_connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/adlfs/spec.py", line 515, in do_connect
    raise ValueError(f"unable to connect to account for {e}")
ValueError: unable to connect to account for Must provide either a connection_string or account_name with credentials!!
[2024-05-02T17:07:05.437+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=write_wikipedia_data, execution_date=20240502T164534, start_date=20240502T170705, end_date=20240502T170705
[2024-05-02T17:07:05.446+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task write_wikipedia_data (unable to connect to account for Must provide either a connection_string or account_name with credentials!!; 535)
[2024-05-02T17:07:05.489+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-02T17:07:05.505+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T17:07:05.506+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
